spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_user_center
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
server:
  port: 8081