spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_user_center
    hikari:
      username: root
      password: 12345678
      # mysql-connector-java >= 6.X com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.X com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
        # 指定namespace(profile)
        #namespace: 404060ce-2e6c-4f72-8083-2beb4ca921ad
        # 指定集群名称
        cluster-name: BJ
    sentinel:
      transport:
        dashboard: localhost:1111
server:
  port: 8081