server:
  port: 1001
spring:
  application:
    name: distributed-transaction
  cloud:
    alibaba:
      seata:
        tx-service-group: geekplus_tx_group  #geekplus_tx_group，server，client都要保持一致\
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_distributed_transactioncd ?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
logging:
  level:
    #com.sxzhongf: debug
    com.sxzhongf.distributed.transaction.feignclients.ISharedCenterFeignClient: debug
feign:
  sentinel:
    enabled: true
  client:
    config:
      # 单服务配置
      #user-center:
      #  loggerLevel: full
      #全局配置
      default:
        loggerLevel: full
  httpclient:
    # 为feign启用 apache httpclient 做请求，而不使用默认的urlconection
    #enabled: true
    # feign 最大连接数
    max-connections: 200
    # feign 单个路径请求的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true