spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_shared_center
    hikari:
      username: root
      password: 12345678
      # mysql-connector-java >= 6.X com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.X com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: shared-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8010