spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_shared_center?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 12345678
      # mysql-connector-java >= 6.X com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.X com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: shared-center
  cloud:
    alibaba:
      seata:
        tx-service-group: geekplus_tx_group  #geekplus_tx_group，server，client都要保持一致
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        cluster-name: NJ
#        #namespace: 404060ce-2e6c-4f72-8083-2beb4ca921ad
#        metadata:
#          # 当前实例版本
#          version: v1
#          # 当前版本的内容中心允许调用的用户中心版本
#          target-version: v1
#    sentinel:
#      datasource:
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            # 规则类型，取值见：com.alibaba.cloud.sentinel.datasource.RuleType
#            rule_type: flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#      transport:
#        # 指定sentinel 控制台的地址
#        dashboard: localhost:1111
#      filter:
#        # 关闭掉对SpringMVC 端点的保护
#        enabled: false

#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8011

user-center: # service name
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 规则类的全路径名称
ribbon:
  eager-load:
    enabled: true # 饥饿加载激活
    clients: user-center # 为哪些clients开启
logging:
  level:
    #com.sxzhongf: debug
    com.sxzhongf.sharedcenter.feignclients.IUserCenterFeignClient: debug
    com.sxzhongf.sharedcenter.feignclients.ITestUserCenterFeignClient: debug
feign:
  sentinel:
    enabled: true
  client:
    config:
      # 单服务配置
      #user-center:
      #  loggerLevel: full
      #全局配置
      default:
        loggerLevel: full
  httpclient:
    # 为feign启用 apache httpclient 做请求，而不使用默认的urlconection
    #enabled: true
    # feign 最大连接数
    max-connections: 200
    # feign 单个路径请求的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  title: content-center-service
  description: provide shared center API
  version: 1.0.0.RC
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: http://www.geekplus.com.cn
  contact:
    email: magicianisaac@gmail.com
    name: Isaac-Zhang
    url: http://www.life-runner.com
  base-package: com.sxzhongf
  base-path: /**