spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shared_platform_shared_center
    hikari:
      username: root
      password: 12345678
      # mysql-connector-java >= 6.X com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.X com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: shared-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: NJ
        #namespace: 404060ce-2e6c-4f72-8083-2beb4ca921ad
        metadata:
          # 当前实例版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

user-center: # service name
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 规则类的全路径名称
ribbon:
  eager-load:
    enabled: true # 饥饿加载激活
    clients: user-center # 为哪些clients开启
logging:
  level:
   #com.sxzhongf: debug
    com.sxzhongf.sharedcenter.feignclients.IUserCenterFeignClient: debug
    com.sxzhongf.sharedcenter.feignclients.ITestUserCenterFeignClient: debug
feign:
  client:
    config:
      defaultSynchronousMethodHandler:
        loggerLevel: full
  httpclient:
    # 为feign启用 apache httpclient 做请求，而不使用默认的urlconection
    #enabled: true
    # feign 最大连接数
    max-connections: 200
    # feign 单个路径请求的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: sentinel