-- -- MySQL Script generated by MySQL Workbench
-- -- Wed Jul 10 14:28:01 2019
-- -- Model: New Model    Version: 1.0
-- -- MySQL Workbench Forward Engineering
--
-- -- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- -- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- -- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
--
-- -- CREATE DATABASE shared_platform;
-- -- -----------------------------------------------------
-- -- Schema shared_platform
-- -- -----------------------------------------------------
--
-- -- -----------------------------------------------------
-- -- Schema shared_platform
-- -- -----------------------------------------------------
-- --
-- -- CREATE SCHEMA IF NOT EXISTS `shared_platform` DEFAULT CHARACTER SET utf8 ;
-- -- USE `shared_platform` ;
--
-- -- -----------------------------------------------------
-- -- Table `shared_platform`.`user`
-- -- -----------------------------------------------------
 CREATE TABLE IF NOT EXISTS `user` (
   `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id',
   `wx_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信id',
   `wx_nickname` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信昵称',
   `roles` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '角色',
   `avatar_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像地址',
   `create_time` DATETIME NOT NULL COMMENT '创建时间',
   `update_time` DATETIME NOT NULL COMMENT '修改时间',
   `bonus` INT NOT NULL DEFAULT 300 COMMENT '积分',
   PRIMARY KEY (`id`))
 COMMENT = '分享';
--
--
-- -----------------------------------------------------
-- Table `shared_platform`.`bonus_event_log`
-- -- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonus_event_log` (
   `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Id',
   `user_id` BIGINT NULL COMMENT 'user.id',
   `value` INT NULL COMMENT '积分操作值',
   `event` VARCHAR(20) NULL COMMENT '发生的事件',
   `create_time` DATETIME NULL COMMENT '创建时间',
   `description` VARCHAR(100) NULL COMMENT '描述',
   PRIMARY KEY (`id`),
   INDEX `fk_bonus_event_log_user1_idx` (`user_id` ASC) VISIBLE)
 ENGINE = InnoDB
 COMMENT = '积分变更记录表';

-- --
-- -- SET SQL_MODE=@OLD_SQL_MODE;
-- -- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- -- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
